export const GAMES = {
  UPDATE: 'GAMES/UPDATE',
  SET_CURRENT_BY_URL: 'GAMES/SET_CURRENT',
  SET_ALREADY_PLAYED_BY_URL: 'GAMES/SET_ALREADY_PLAYED',
};

export const TEAMS = {
  UPDATE: 'TEAMS/UPDATE',
  ADD_POINTS: 'TEAMS/ADD_POINTS',
};
